# Generated by Django 3.0.5 on 2020-04-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
