# Generated by Django 3.0.5 on 2020-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_auto_20200406_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateField(verbose_name=0),
        ),
    ]
