# Generated by Django 3.0.5 on 2020-04-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_auto_20200406_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateField(),
        ),
    ]
