# Generated by Django 3.0.5 on 2020-04-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_auto_20200406_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='date',
        ),
    ]
